# Generated by Django 5.2.12 on 2026-09-10 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_backfill_partner_last_seen'),
        ('malahi_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='malahiprovider',
            name='cities',
            field=models.ManyToManyField(blank=True, help_text='Cities this venue operates in (synced from the Malahi catalog)', related_name='malahi_providers', to='base.city'),
        ),
        migrations.AddField(
            model_name='malahiprovider',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Supplier record used when transacting with this venue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malahi_providers', to='base.partner'),
        ),
    ]
